"""empty message

Revision ID: 89dab8d2da3b
Revises: 
Create Date: 2025-03-18 00:07:14.863213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89dab8d2da3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_requests',
    sa.Column('data_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.Column('initial_balance', sa.Integer(), nullable=False),
    sa.Column('trade_day', sa.Integer(), nullable=False),
    sa.Column('fee_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('weight_months', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('data_id')
    )
    op.create_index(op.f('ix_backtest_requests_data_id'), 'backtest_requests', ['data_id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=13, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', name='uq_prices_date_ticker')
    )
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_table('nav',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nav_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['backtest_requests.data_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nav_id'), 'nav', ['id'], unique=False)
    op.create_table('rebalance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['backtest_requests.data_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rebalance_id'), 'rebalance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rebalance_id'), table_name='rebalance')
    op.drop_table('rebalance')
    op.drop_index(op.f('ix_nav_id'), table_name='nav')
    op.drop_table('nav')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_backtest_requests_data_id'), table_name='backtest_requests')
    op.drop_table('backtest_requests')
    # ### end Alembic commands ###
