"""empty message

Revision ID: a1c16b2e822e
Revises: 8355a458f5c5
Create Date: 2025-03-26 18:38:48.615002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c16b2e822e'
down_revision: Union[str, None] = '8355a458f5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_id', table_name='prices')
    op.drop_column('prices', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_prices_id', 'prices', ['id'], unique=False)
    # ### end Alembic commands ###
